"""Build an emulator profile from an atem-sweep golden record.

    python make_profile.py ../sweep/golden/atem-mini_sdk10.2.1_proto2.30 profiles/atem-mini_proto2.30

Writes, into the profile folder:
  dump.txt    the state the real switcher sends when a client connects, one
              field per line ("NAME HEX"), in the order the switcher sent it
  macros.txt  what each stored macro changed when the sweep ran it
              ("INDEX NAME HEX"), replayed by the emulator on MAct run
"""
import json
import os
import sys

# Fields sent with every packet or derived from other state; not macro effects.
NOT_MACRO_EFFECTS = {'Time', 'TlIn', 'TlSr', 'FMTl', 'MRPr'}


def connect_dump(wire_path):
    """Fields of the first connect dump: switcher -> client, up to InCm."""
    fields = []
    with open(wire_path, encoding='utf-8') as f:
        for line in f:
            pkt = json.loads(line)
            if pkt['dir'] != 'rx':
                continue
            for field in pkt['fields']:
                fields.append((field['field'], field['hex']))
                if field['field'] == 'InCm':
                    return fields
    raise SystemExit('no InCm (end of connect dump) in ' + wire_path)


def macro_effects(results_path):
    with open(results_path, encoding='utf-8') as f:
        results = json.load(f)
    effects = {}
    for test in results['tests']:
        parts = test['id'].split('.')   # macro.run.<slot>; not macro.run.bad.100
        if len(parts) != 3 or parts[:2] != ['macro', 'run'] or not parts[2].isdigit():
            continue
        if test['status'] != 'pass':
            continue
        index = int(parts[2])
        rx = test.get('wire', {}).get('rx', [])
        effects[index] = [(f['field'], f['hex']) for f in rx if f['field'] not in NOT_MACRO_EFFECTS]
    return effects


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    golden, out = sys.argv[1], sys.argv[2]
    os.makedirs(out, exist_ok=True)
    source = os.path.basename(os.path.normpath(golden))

    dump = connect_dump(os.path.join(golden, 'wire.jsonl'))
    with open(os.path.join(out, 'dump.txt'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(f'# Connect dump recorded from the real switcher ({source}).\n')
        f.write('# One field per line: NAME HEX. Generated by make_profile.py.\n')
        for name, hexdata in dump:
            f.write(f'{name} {hexdata}\n')

    effects = macro_effects(os.path.join(golden, 'results.json'))
    with open(os.path.join(out, 'macros.txt'), 'w', encoding='utf-8', newline='\n') as f:
        f.write(f'# Fields each stored macro changed when run on the real switcher ({source}).\n')
        f.write('# One field per line: INDEX NAME HEX. Generated by make_profile.py.\n')
        for index in sorted(effects):
            for name, hexdata in effects[index]:
                f.write(f'{index} {name} {hexdata}\n')

    print(f'{out}: {len(dump)} dump fields, {len(effects)} macros '
          f'({sum(len(v) for v in effects.values())} effect fields)')


if __name__ == '__main__':
    main()
