"""Writes core/src/setters_table.inc from setters_spec.py.

    python gen_setters.py

The emulator core applies every "set value" command in this table with one
generic handler (Device::applySetter). Change setters_spec.py, prove it with
check_setters.py against a golden record, then run this.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from setters_spec import SETTERS, EQ_RANGES  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'setters_table.inc')

RULES = {None: 'None', 'clamp': 'Clamp', 'mod': 'Mod', 'allow': 'Allow', 'ignore': 'Ignore',
         'unitwrap': 'UnitWrap', 'negdec': 'NegDec', 'allowbits': 'AllowBits', 'eqfreq': 'EqFreq',
         'refuseif': 'RefuseIf'}
POSTS = {None: 'None', 'keyframeStored': 'KeyframeStored', 'chromaCursor': 'ChromaCursor',
         'transitionRate': 'TransitionRate'}


def ident(cmd, name):
    return f'k{cmd}_{name}'


def main():
    out = ['// Generated by core/tools/gen_setters.py from setters_spec.py. Do not edit.',
           '// Included by device.cpp inside namespace emu::setters.', '']
    for cmd, spec in SETTERS.items():
        props = spec['props']
        for p in props:
            rule = p['rule']
            if rule and rule[0] == 'allow':
                vals = ', '.join(str(v) for v in sorted(rule[1]))
                out.append(f'constexpr qint64 {ident(cmd, p["name"])}_set[] = {{ {vals} }};')
            if rule and rule[0] == 'refuseif':
                vals = ', '.join(str(v) for v in sorted(rule[2]))
                out.append(f'constexpr qint64 {ident(cmd, p["name"])}_set[] = {{ {vals} }};')
            for other, table in (p.get('effects') or {}).items():
                q = next(x for x in props if x['name'] == other)
                rows = ', '.join(f'{{ {v}, {q["field"]}, {q["size"]}, {w} }}' for v, w in sorted(table.items()))
                out.append(f'constexpr Effect {ident(cmd, p["name"])}_effects[] = {{ {rows} }};')
        lines = []
        for p in props:
            rule = p['rule']
            kind = RULES[rule[0] if rule else None]
            a = b = 0
            setp, setn = 'nullptr', 0
            if rule and rule[0] == 'clamp':
                a, b = rule[1], rule[2]
            elif rule and rule[0] == 'mod':
                a = rule[1]
            elif rule and rule[0] == 'unitwrap':
                a, b = (rule[1], 1) if rule[1] is not None else (0, 0)   # b: has a minimum
            elif rule and rule[0] in ('allowbits', 'eqfreq'):
                a = rule[1]
            elif rule and rule[0] == 'refuseif':
                a = rule[1]
            if rule and rule[0] in ('allow', 'refuseif'):
                setp = f'{ident(cmd, p["name"])}_set'
                setn = len(rule[1] if rule[0] == 'allow' else rule[2])
            eff, effn = 'nullptr', 0
            for other, table in (p.get('effects') or {}).items():
                eff, effn = f'{ident(cmd, p["name"])}_effects', len(table)
            also = p.get('also')
            also_field, also_off = (f'"{also[0]}"', also[1]) if also else ('nullptr', 0)
            bit = -1 if p['bit'] is None else p['bit']
            lines.append(f'    {{ {bit}, {p["cmd"]}, {p["field"]}, {p["size"]}, {str(p["signed"]).lower()}, '
                         f'Rule::{kind}, {a}, {b}, {setp}, {setn}, {str(p["echoSame"]).lower()}, '
                         f'{also_field}, {also_off}, {eff}, {effn} }},   // {p["name"]}')
        out.append(f'constexpr Prop k{cmd}_props[] = {{')
        out += lines
        out.append('};')
        keys = ', '.join(f'{{ {c}, {f} }}' for c, f in spec['key'])
        if spec['key']:
            out.append(f'constexpr KeyByte k{cmd}_key[] = {{ {keys} }};')
        out.append('')
    out.append('constexpr Setter kSetters[] = {')
    for cmd, spec in SETTERS.items():
        keyp = f'k{cmd}_key' if spec['key'] else 'nullptr'
        out.append(f'    {{ "{cmd}", "{spec["field"]}", {spec["mask"]}, {keyp}, {len(spec["key"])}, '
                   f'{str(spec.get("echoSame", True)).lower()}, Post::{POSTS[spec.get("post")]}, '
                   f'k{cmd}_props, {len(spec["props"])} }},')
    out.append('};')
    out.append('')
    rows = ', '.join(f'{{ {r}, {lo}, {hi} }}' for r, (lo, hi) in sorted(EQ_RANGES.items()))
    out.append(f'constexpr EqRange kEqRanges[] = {{ {rows} }};')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(out) + '\n')
    print(f'wrote {OUT}: {len(SETTERS)} commands, {sum(len(s["props"]) for s in SETTERS.values())} values')


if __name__ == '__main__':
    main()
